---
- hosts: webserver
  become: yes
  become_method: sudo
  vars:
    http_port: 80
    email: howdy140@gmail.com

  tasks:
    - name: update apt and install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
    - name: install letsencrypt client
      apt:
        name: python-certbot-nginx
        state: latest
    - name: copy default server block
      command: cp /etc/nginx/sites-available/default /etc/nginx/sites-available/thegreekbrit.com
    - name: modify server block to use domain
      command: sed -i 's/server_name _/server_name thegreekbrit\.com/g;s/# listen 443/listen 443/g' /etc/nginx/sites-available/thegreekbrit.com
    - name: move default server block
      command: mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
    - name: enable new server block
      command: ln -s /etc/nginx/sites-available/thegreekbrit.com /etc/nginx/sites-enabled/
    - name: restart nginx
      command: systemctl restart nginx.service
    - name: fetch & install LE certificate
      command: /usr/bin/certbot --authenticator webroot --webroot-path /var/www/html -m {{ email }} -d thegreekbrit.com --installer nginx --non-interactive --agree-tos
